#!/bin/bash
# install sublime
#
# . sublime/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
	CURRENT=${PWD} && cd -P "$( dirname "$0" )" && cd .. && . ./config && cd $CURRENT
fi

install_package_control () {
	curl http://sublime.wbond.net/Package%20Control.sublime-package -o "$CONFIG__package_control_file"
}

setup_sublime () {
	echo "Setting up Sublime..."
	# symlink sublime user preferences
	if [ -e "${CONFIG__packages_path}/Packages" ]; then
		read -p "Sublime /Packages directory already exists... overrwrite with symlink? [y(es)/n(o)] "
		if [[ $REPLY =~ ^(yes|y)$ ]]; then
			rm -r "${CONFIG__packages_path}/Packages"
		fi
	fi
	ln -s "$OSZ_ROOT/sublime/Packages" "$CONFIG__packages_path"

	# symlink emmet prefs
	ln -s "$OSZ_ROOT/emmet.link" "$HOME/.emmet"

	# install package control
	if [ ! -f "$CONFIG__package_controle_file" ]; then
		echo "Installing package control..."
		install_package_control
	fi

	# add sublime command
	if [ ! -f /usr/local/bin/sublime ]; then
		echo "Adding sublime command to command line..."
		ln -s "$CONFIG__sublime_path" /usr/local/bin/sublime
	fi

	# set as default text editor
	echo "Setting Sublime as default editor..."
	defaults write com.apple.LaunchServices LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=com.sublimetext.3;}'
	echo "DONE."
}

setup_sublime
