#!/usr/bin/env bash
#
# install sublime

install_package_control () {
	curl http://sublime.wbond.net/Package%20Control.sublime-package -o "$package_control_file"
}

function setup_sublime () {
	local package_control_file="$HOME/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"

	# symlink all user preferences
	link_file "$OSZ_ROOT/sublime/Packages" "$HOME/Library/Application Support/Sublime Text 3/Packages"

	# install package control
	if [ -f "$package_controle_file" ]; then
		overwrite_handler "$package_controle_file" && install_package_control && log "Installed package control."
	else
		install_package_control
	fi

	# add sublime command
	if [ ! -f /usr/local/bin/sublime ]; then
		ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
		log "Added sublime command to command line."
	fi

	# set as default text editor
	defaults write com.apple.LaunchServices LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=com.sublimetext.3;}'
	log "Set Sublime as default macOS text editor."
}

setup_sublime