#!/bin/bash

CONFIG__sublime_path="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
CONFIG__packages_path="$HOME/Library/Application Support/Sublime Text 3"

if [ -z $OSZ_PATH ]; then
	read -e -p "[??] Where is OS Zimmee installed? " -i "$HOME/Projects/os-zimmee" OSZ_PATH
fi

init () {
	setup_dotfiles
	setup_sublime
	# Done.
	echo "Sublime setup complete!"
	echo "Sublime should automatically install packages after you install package control from the command palette. If the packages do not automatically install, do the following:"
	echo "  1) After package control is installed, open ~/Projects/os-zimmee/sublime/Packages/User/Package\ Control.sublime-settings."
	echo "  2) Create a comma-delimited list from the \`installed_packages\` property."
	echo "  3) Type \`advanced install\` in the command prompt and paste the comma-delimited list of packages."
}

install_package_control () {
	curl http://sublime.wbond.net/Package%20Control.sublime-package -o "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"
}

setup_sublime () {
	echo "Setting up Sublime..."
	# Symlink sublime user preferences.
	rm -rf "${CONFIG__packages_path}/Packages"
	ln -sf "$OSZ_PATH/sublime/Packages" "${CONFIG__packages_path}/Packages"

	# Set as default text editor.
	printf 'Set Sublime as default text editor? [y(es)/n(o)]'
	read REPLY
	if [[ $REPLY =~ ^(yes|y)$ ]]; then
		defaults write com.apple.LaunchServices LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=com.sublimetext.3;}'
	fi
}

setup_dotfiles () {
	for dotfile in $(find ${OSZ_PATH}/sublime -name '*.link'); do
		dest="$HOME/.$(basename "${dotfile%.*}")"
		if [[ $(readlink "$dest") != "$dotfile" ]]; then
			ln -sf "$dotfile" "$dest"
		fi
	done
}

init