#!/bin/bash

sublime_path="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
packages_path="$HOME/Library/Application Support/Sublime Text"

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

uninstall () {
	uninstall_sublime
	uninstall_package_control
	remove_sublime
	echo "Sublime uninstall complete!"
}

uninstall_package_control () {
	rm -rf "$packages_path/Installed Packages/Package Control.sublime-package"
}

uninstall_sublime () {
	brew list --casks sublime-text && brew uninstall sublime-text
}

remove_sublime () {
	echo "Removing Sublime configurations..."

	# Remove sublime user preferences to OS Zimmee.
	rm -rf "${packages_path}/Packages"

	# Remove subl CLI executable.
	rm -rf $HOME/bin/subl
}

uninstall
