#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
  read -e -p "[?] Where is OS Zimmee installed? " -i "$HOME/Projects/os-zimmee" reply
  OSZ_ROOT=$reply
fi

# Ask whether to overwrite existing files.
OVERWRITE_EXISTING=false
read -p "Should existing dotfiles be overwritten? (y/N) " OVERWRITE_EXISTING
if [[ $REPLY =~ ^(yes|y)$ ]]; then
  OVERWRITE_EXISTING=true
fi

# Get config.
source $OSZ_ROOT/dotfiles/config.sh

# Symlink dotfiles.
for DOTFILE in ${CONFIG__DOTFILES[@]}; do
	dest="$HOME/$DOTFILE"
  source="$OSZ_ROOT/dotfiles/$DOTFILE"
	if [[ $OVERWRITE_EXISTING = true ]]; then
		ln -sf "$source" "$dest"
	else
		ln -s "$source" "$dest" || echo "Skipped $DOTFILE."
	fi
	echo "Set up $DOTFILE!"
done
