#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Ask whether to overwrite existing files.
overwrite_existing=false
read -p "Should existing dotfiles be overwritten? (y/N) " reply
if [[ $reply =~ ^(yes|y)$ ]]; then
  overwrite_existing=true
fi

# Symlink dotfiles.
for dotfile in $HOME/Projects/os-zimmee/dotfiles/.[^.]*; do
	if [[ -f $dotfile ]]; then
		dest="$HOME/$dotfile"
		source="$OSZ_ROOT/dotfiles/$dotfile"
		if [[ $overwrite_existing = true ]]; then
			ln -sf "$source" "$dest"
		else
			ln -s "$source" "$dest" || echo "Skipped $dotfile."
		fi
		echo "Set up $dotfile!"
	fi
done
