#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Remove dotfiles.
for dotfile in $HOME/Projects/os-zimmee/dotfiles/.[^.]*; do
	if [[ -f $dotfile ]]; then
		dest="$HOME/$dotfile"
		rm -rf "$dotfile" "$dest"
	fi
done

echo 'Removed all dotfiles!'
