#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
  read -e -p "[??] Where is OS Zimmee installed? " -i "$HOME/Projects/os-zimmee" reply
  OSZ_ROOT=$reply
fi

# Get config.
source $OSZ_ROOT/dotfiles/config.sh

# Symlink dotfiles.
for DOTFILE in ${CONFIG__DOTFILES[@]}; do
	dest="$HOME/$DOTFILE"
	rm -rf "$DOTFILE" "$dest"
done

echo 'Removed all dotfiles!'
