#!/usr/bin/env bash
#
# simple logging utilities

## colors
BOLD="\033[1m"
END_BOLD="\033[21m"
DIM="\033[2m"
END_DIM="\033[22m"
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
END_COLOR="\033[0m"

INFO_PREFIX="[ ${BLUE}..${END_COLOR} ]"
IMPORTANT_PREFIX="[ ${BOLD}${YELLOW}!!${END_COLOR} ]${BOLD}"
QUESTION_PREFIX="[ ${YELLOW}??${END_COLOR} ]"
SUCCESS_PREFIX="[ ${GREEN}OK${END_COLOR} ]${GREEN}"
FAIL_PREFIX="[${BOLD}${RED}FAIL${END_COLOR}]${RED}"

LOG_INDENT="       "

## helper functions
# log info to the cli
log () {
    # set defaults
    local msg='' log=$1 type=${2:-info} title=${3:-$title} suffix=${4:-'\n'} log_prefix=$log_prefix
    # add log prompt prefix
    if [[ ! -z "$log_prefix" ]] && [[ "$log_prefix" != "false" ]]; then
        msg+="${log_prefix} "
    else
        case "$type" in
            question)
                msg+="${QUESTION_PREFIX} ";;
            important)
                msg+="${IMPORTANT_PREFIX} ";;
            success)
                msg+="${SUCCESS_PREFIX} ";;
            fail)
                msg+="${FAIL_PREFIX} ";;
            info)
                msg+="${INFO_PREFIX} ";;
            *)
                msg+="${INFO_PREFIX} ";;
        esac
    fi
    # text styles for the line
    [[ $type = important ]] && msg+="${BOLD}"
    # add msg title
    if [[ ! -z $title ]]; then
        msg+="${END_COLOR}[${BLUE}${title}${END_COLOR}] "
    fi
    # add default msg color
    if [[ $type = question ]]; then
        msg+="${YELLOW}"
    elif [[ $type = fail ]]; then
        msg+="${RED}"
    fi
    # build log msg
    msg+="${log}${END_COLOR}${suffix}"
    echo -en "$msg"
}
# ask for user input
ask () {
    log "$1" question "$title" " "
    read -r $2 < /dev/tty
}
# ask for a y|n response
yes_no () {
    log "${1} ${CYAN}[y|n]" question "$title" " "
    read -n 1 -r "$2" < /dev/tty
    echo ''
    [[ ! ${!2} =~ ^(y|n)$ ]] && log 'Not a valid response' important && yes_no "$@"
}
# continue when ready
continue_when_ready () {
    local msg="${1:-Hit ${CYAN}[enter]${END_COLOR} to continue.}"
    local value=${2:-''}
    ask "$msg" user_input
    [[ $user_input = "$value" ]] && return 0 || log 'Not a valid response.' important && continue_when_ready "$@"
}
# throw an error and quit
fail () {
    local msg="$1" should_exit="$2"
    log "$msg" fail
    echo ''
    [[ $should_exit ]] && exit
}

# export -f log
# export -f ask
# export -f yes_no
# export -f fail
# export -f continue_when_ready