#!/usr/bin/env bash
# Set up git and ssh

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

## Set up SSH key.
setup_ssh () {
	git_exists=false
	[ -x "$(command -v git)" ] && git_exists=true

	if [ $git_exists = true ]; then
		git_email=$(git config user.email)
	else
		read -p "[?] What email address would you like to use for the ssh key? " git_email
	fi
	# Generate SSH.
	# LEGACY WAY: ssh-keygen -t rsa -b 4096 -C "${git_email}"
	ssh-keygen -t ed25519 -C "${git_email}"

	# Symlink ssh config.
	ln -s $OSZ_ROOT/git/ssh-config $HOME/.ssh/config

	# Start up SSH agent.
	eval "$(ssh-agent -s)"
	# LEGACY WAY: ssh-add $HOME/.ssh/id_rsa
	ssh-add $HOME/.ssh/id_ed25519

	# Copy SSH to clipboard.
	# LEGACY WAY: pbcopy < $HOME/.ssh/id_rsa.pub
	pbcopy < $HOME/.ssh/id_ed25519.pub
	read -n 1 -s -r -p "[!!] Your SSH key has been copied to the clipboard; paste it into your GitHub account (https://github.com/account/ssh). Then hit any key to continue... "
}

install () {
	# Set up gitconfig.
	echo "Installing git..."

	# Install git from homebrew.
	brew install git

	# Set up git configurations.
	echo "Setting up git configs..."
	gitconfig_local=$HOME/.gitconfig-local
	continue=y
	if [ -f $gitconfig_local ]; then
		read -p "$gitconfig_local already exists. Overwrite it? (y/N) " continue
		continue=${continue:-n}
		if [[ $continue =~ ^(yes|y)$ ]]; then
			mv -f $gitconfig_local "${gitconfig_local}-backup"
			echo "[i] Existing $gitconfig_local moved to ${gitconfig_local}-backup"
		fi
	fi
	if [[ $continue =~ ^(yes|y)$ ]]; then
		cp -rf $OSZ_ROOT/git/.gitconfig-local-default $gitconfig_local	
	fi

	ln -sf ${OSZ_ROOT}/git/.gitignore $HOME/.gitignore
	ln -sf ${OSZ_ROOT}/git/.gitconfig $HOME/.gitconfig

	# Set up SSH key.
	echo "Creating SSH key... "
	if [[ -e $HOME/.ssh/id_ed25519 ]]; then
		read -p "An SSH key may already exist. Create a new one (and potentially overwrite the old)? (y/N) "
		if [[ $REPLY =~ ^(yes|y)$ ]]; then
			# LEGACY WAY: rm -rf $HOME/.ssh/id_rsa
			rm -rf $HOME/.ssh/id_ed25519
			echo 'SSH key removed.'
			setup_ssh
		fi
	else
		setup_ssh
	fi

	## WRAP IT UP.
	echo "[ok] git install complete."
}

install