#!/usr/bin/env bash
# set up git and ssh
#
# TO RUN:
# . git/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
	CURRENT=${PWD} && cd -P "$( dirname "$0" )" && cd .. && . ./config && cd $CURRENT
fi

# create new key
echo "Creating new SSH key... "

ssh-keygen -t rsa -b 4096 -C "${CONFIG__git_useremail}"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
pbcopy < ~/.ssh/id_rsa.pub

# set up gitconfig
echo "Setting up ~/.gitconfig and ~/.gitignore-global..."

ln -s ${OSZ_ROOT}/git/gitignore.link ~/.gitignore-global
ln -s ${OSZ_ROOT}/git/gitconfig.link ~/.gitconfig

if [[ -z $CONFIG__git_username ]] || [[ -z $CONFIG__git_useremail ]]; then
    echo "(user choice) gitconfig was skipped. No user name or email."
    return 1
else
    cat ${OSZ_ROOT}/git/gitconfig.local | sed -e "s/AUTHORNAME/$CONFIG__git_username/g" -e "s/AUTHOREMAIL/$CONFIG__git_useremail/g" -e "s/GIT_CREDENTIAL_HELPER/$CONFIG__git_credential/g" > "$HOME/.gitconfig.local"
fi

echo "A new SSH key was created, as well as .gitconfig and .gitignore-global files. The SSH key was copied to your clipboard; make sure to paste it into your GitHub account (https://github.com/account/ssh)."