#!/usr/bin/env bash
# uninstall git and ssh

uninstall () {
	# Set up gitconfig.
	echo "Uninstalling git configurations..."

	rm -rf ~/.gitconfig-local
	rm -rf ~/.gitignore
	rm -rf ~/.gitconfig

	# Remove SSH key.
	if [[ -e $HOME/.ssh/id_ed25519 ]]; then
		read -p "Remove your existing SSH key? (y/N) " reply
		if [[ $reply =~ ^(yes|y)$ ]]; then
			rm -rf ~/.ssh
			echo "Removed SSH key!"
		fi
	fi

	## WRAP IT UP.
	echo "[ok] git uninstall complete."
}

uninstall
