#!/usr/bin/env bash
#
# config to install everything with no questions asked

# shows config is loaded
CONFIG__loaded=true

# OS ROOT
OSZ_ROOT=~/Projects/os-zimmee

# homebrew taps / repos to install with `brew tap <tap>`
CONFIG__brew_taps=(
    caskroom/cask
    homebrew/versions
    caskroom/fonts
)
# homebrew apps to install with `brew install <app>`
CONFIG__brew_apps=(
    bash
    git
    # homebrew/binary/kwm
    imagemagick
    mas
    node
    wget
    zsh
)
# homebrew cask apps to install with `brew cask install <app>`
CONFIG__cask_apps=(
    # amethyst
    1password
    appcleaner
    blisk
    brave
    colorpicker
    cyberduck
    filezilla
    firefox
    firefoxdeveloperedition
    flux
    # forklift
    google-chrome
    google-chrome-canary
    # google-drive
    hammerspoon
    # hyper
    iterm2
    karabiner-elements
    # karabiner
    # little-snitch
    parallels-desktop
    private-internet-access
    # seil
    slack
    sublime-text-dev
    torbrowser
    unifi-controller
    # osx quicklook plugins
    betterzipql
    qlcolorcode
    qlimagesize
    qlmarkdown
    qlprettypatch
    qlstephen
    quicklook-csv
    quicklook-json
    unarchiver
    webpquicklook
    # fonts
    font-bebas-neue
    font-inconsolata
    font-inconsolata-for-powerline
    font-open-sans
)
# node packages to install GLOBALLY with `npm install -g <package>`
CONFIG__npm_globals=(
    "gulp-cli"
)

# git & ssh
CONFIG__git_username="The Zimmee"
CONFIG__git_useremail="thezimmee@gmail.com"
CONFIG__sshkey="$HOME/.ssh/id_rsa.pub"
CONFIG__git_credential='osxkeychain'

# sublime
CONFIG__sublime_path="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
CONFIG__packages_path="$HOME/Library/Application Support/Sublime Text 3"
CONFIG__package_control_file="$HOME/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"
