#!/usr/bin/env bash
#
# config to install everything with no questions asked

# homebrew taps / repos to install with `brew tap <tap>`
CONFIG__brew_taps=(
    caskroom/cask
    caskroom/versions
    caskroom/fonts
)
# homebrew apps to install with `brew install <app>`
CONFIG__brew_apps=(
    bash
    git
    homebrew/binary/kwm
    imagemagick
    mas
    node
    wget
    zsh
)
# homebrew cask apps to install with `brew cask install <app>`
CONFIG__cask_apps=(
    amethyst
    appcleaner
    colorpicker
    filezilla
    firefox
    firefoxdeveloperedition
    google-chrome
    google-chrome-canary
    hammerspoon
    iterm2
    karabiner
    seil
    slack
    sublime-text
    # osx quicklook plugins
    betterzipql
    qlcolorcode
    qlimagesize
    qlmarkdown
    qlprettypatch
    qlstephen
    quicklook-csv
    quicklook-json
    webpquicklook
    # fonts
    font-bebas-neue
    font-inconsolata
    font-inconsolata-for-powerline
    font-open-sans
)
# node packages to install GLOBALLY with `npm install -g <package>`
CONFIG__npm_globals=(
    "gulp-cli"
)

# git & ssh
CONFIG__git_username="The Zimmee"
CONFIG__git_useremail="thezimmee@gmail.com"
CONFIG__sshkey="$HOME/.ssh/id_rsa.pub"

## setup options (bootstrap will ask you for these values unless you add them here)
# CONFIG__run_type=install # install | setup | update
# CONFIG__run_mode=ask # ask | overwrite | backup | preserve