#!/usr/bin/env bash
#
# config to install everything with no questions asked

# shows config is loaded
CONFIG__loaded=true

# OS ROOT
OSZ_ROOT=~/Projects/os-zimmee

# homebrew taps / repos to install with `brew tap <tap>`
CONFIG__brew_taps=(
	caskroom/cask
	caskroom/fonts
)
# homebrew apps to install with `brew install <app>`
CONFIG__brew_apps=(
	bash
	fasd
	git
	# homebrew/binary/kwm
	imagemagick
	lua
	mas
	nvm
	tidy-html5
	wget
	zsh
	zsh-completions
)
# homebrew cask apps to install with `brew cask install <app>`
CONFIG__cask_apps=(
	## [[APPS]]
	# amethyst
	# 1password
	airmail-beta
	alfred
	appcleaner
	# blisk
	beyond-compare
	brave
	# colorpicker
	# cyberduck
	# filezilla
	firefox
	firefoxdeveloperedition
	# flux
	forklift
	goodsync
	google-chrome
	caskroom/versions/google-chrome-canary
	# google-drive
	hammerspoon
	hazeover
	# hyper
	iterm2
	karabiner-elements
	# karabiner
	# kindle
	lastpass
	# little-snitch
	musescore
	opera
	parallels
	# plex-media-server
	# private-internet-access
	# seil
	slack
	caskroom/versions/sublime-text-dev
	# teamviewer
	# torbrowser
	time-out
	caskroom/drivers/ubiquiti-unifi-controller
	vivaldi
	witch
	## [[QUICKLOOK PLUGINS]]
	betterzipql
	qlcolorcode
	qlimagesize
	qlmarkdown
	qlprettypatch
	qlstephen
	quicklook-csv
	quicklook-json
	the-unarchiver
	webpquicklook
	## [[FONTS]]
	font-bebas-neue
	font-consolas-for-powerline
	font-dejavu-sans-mono-for-powerline
	font-droid-sans-mono-for-powerline
	font-fira-mono-for-powerline
	font-inconsolata
	font-inconsolata-for-powerline
	font-menlo-for-powerline
	font-meslo-for-powerline
	font-open-sans
	font-roboto-mono-for-powerline
	font-source-code-pro-for-powerline
	font-ubuntu-mono-derivative-powerline
)
# node packages to install GLOBALLY with `npm install -g <package>`
CONFIG__npm_globals=(
	"eslint"
	"prettier"
	"stylelint"
)

# git & ssh
CONFIG__git_username="The Zimmee"
CONFIG__git_useremail="thezimmee@gmail.com"
CONFIG__sshkey="$HOME/.ssh/id_rsa.pub"
CONFIG__git_credential='osxkeychain'

# sublime
CONFIG__sublime_path="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
CONFIG__packages_path="$HOME/Library/Application Support/Sublime Text 3"
CONFIG__package_control_file="$HOME/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"
