#!/usr/bin/env bash
# Installs and configure OS Zimmee.


OSZ_REPO=https://github.com/thezimmee/os-zimmee
OSZ_PATH=${OSZ_PATH:-~/Projects/os-zimmee}
ERROR_MSG=""


setup () {
	INSTALL_APPS=y
	CONFIRM_MSG=""

	# Intro.
	echo '--- OS ZIMMEE INSTALL WIZARD ---'
	echo "[i] This wizard will help you set up OS Zimmee apps."

	# OS Zimmee path.
	read -e -p "[??] Where should OS Zimmee be installed to? " -i "$OSZ_PATH" OSZ_PATH
	read -p "[?] Installing to ${OSZ_PATH}. Is this correct? (Y/n) " CONTINUE
	CONTINUE=${CONTINUE:-y}
	if [[ $CONTINUE =~ ^([nN][oO]|[nN])$ ]]; then
		echo '[!!] Run installer again to start from the beginning.'
		exit 1
	fi

	# Clone OS Zimmee repo.
	clone_repo || ERROR_MSG="[!!] Something went wrong with cloning OS Zimmee." && exit 1

	# Install homebrew and apps.
	. ${OSZ_PATH}/homebrew/setup || ERROR_MSG+="[!!] Homebrew setup failed. :(\n"

	# Install other apps.
	run_setups

	# Run post install report.
	install_report
}

clone_repo () {
	CONTINUE=y
	if [ -d ${OSZ_PATH} ]; then
		read -p "[?] Path to ${OSZ_PATH} already exists. Overwrite and re-clone? (Y/n) " CONTINUE
		if [[ $CONTINUE =~ ^([nN][oO]|[nN])$ ]]; then
			rm -rf $OSZ_PATH
			CONTINUE=n
		fi
	fi
	if [[ $CONTINUE == y ]]; then
		echo "Cloning ${OSZ_REPO} to ${OSZ_PATH}..."
		git clone --recursive "$OSZ_REPO" "$OSZ_PATH"
	fi
}

run_setups () {
	# Set up other apps.
	echo "Running OS Zimmee setups..."
	for dir in ${OSZ_PATH}/*; do
		if [[ -d "$dir" && ${dir} != homebrew && -f "$dir/setup" ]]; then
			read -p "[?] Do you want to set up ${dir}? (Y/n) " CONTINUE
			CONTINUE=${CONTINUE:-y}
			if [[ $CONTINUE =~ ^([yY][eE][sS]|[yY])$ ]]; then
				. ${OSZ_PATH}/${dir}/setup || ERROR_MSG+="[!!] ${dir} setup failed. :(\n"
			fi
		fi
	done
}

install_report () {
	# wrap up
	if [[ "$ERROR_MSG" != "" ]]; then
		echo "[!!] Uh oh, there was a problem..."
		echo -e "${ERROR_MSG}"
		echo "---"
		echo "Either try again or manually set up the missing pieces listed above."
	else
		echo -e "[ok] Woot woot! OS Zimmee setup is complete!"
		echo -e "[ok] To set up individual apps, simply run \`<os-zimmee path>/<app directory>/setup\`."
		echo -e "[ok] Enjoy!!! :)"
	fi
	echo ''
}

# install & update
setup
