#!/usr/bin/env bash

#!/usr/bin/env bash
# Installs and configure OS Zimmee.


OSZ_REPO=https://github.com/thezimmee/os-zimmee
OSZ_ROOT=${OSZ_ROOT:-~/Projects/os-zimmee}
error_msg=""

uninstall () {
  # OS Zimmee path.
  read -p "[?] Where is OS Zimmee installed? " reply
  OSZ_ROOT=${reply:-$OSZ_ROOT}

  # Uninstall homebrew.
  echo 'Uninstalling homebrew...'
  source ${OSZ_ROOT}/homebrew/uninstall || error_msg+="[!!] Homebrew uninstall failed. :(\n"

  # Uninstall node.
  echo 'Uninstalling node...'
  source ${OSZ_ROOT}/node/uninstall || error_msg+="[!!] Node uninstall failed. :(\n"

  uninstall_apps
  uninstall_report
}

# Uninstall apps.
uninstall_apps () {
  echo "Uninstalling OS Zimmee apps..."
  for dir in ${OSZ_ROOT}/*; do
    if [[ -d "$dir" && ${dir} != homebrew && ${dir} != node && -f "$dir/uninstall" ]]; then
      read -p "[?] Do you want to uninstall ${dir}? (Y/n) " continue
      continue=${continue:-y}
      if [[ $continue =~ ^([yY][eE][sS]|[yY])$ ]]; then
        echo "Uninstalling ${dir}"
        source ${OSZ_ROOT}/${dir}/uninstall || error_msg+="[!!] ${dir} uninstall failed. :(\n"
      fi
    fi
  done
}

# Run post install report.
uninstall_report () {
  # wrap up
  if [[ "$error_msg" != "" ]]; then
    echo "[!!] Uh oh, there was a problem..."
    echo -e "${error_msg}"
  else
    echo -e "[ok] OS Zimmee uninstall complete!"
  fi
  echo ''
}

# Uninstall
uninstall
