#!/usr/bin/env bash
#
# uninstall homebrew and other apps (see http://digitizor.com/install-homebrew-osx-el-capitan/)

## uninstall node (http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally)
echo -e "[ .. ] Removing NPM packages..."
npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm

## uninstall homebrew
echo -e "[ .. ] Removing Homebrew..."
brew cleanup
# remove homebrew directories
rm -rf /usr/local/Cellar
rm -rf /usr/local/.git
# run homebrew uninstall sript
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

## wrap up
echo -e "[ OK ] Done! Uninstall complete."
# echo -e "[ .. ] Note: To fix permission issues with Homebrew, see http://digitizor.com/fix-homebrew-permissions-osx-el-capitan/"
echo ''