#!/usr/bin/env bash
# updates OS Zimmee
#
# bash update

# load config
if [[ -z $CONFIG__loaded ]]; then
	CURRENT=${PWD} && cd -P "$( dirname "$0" )" && bash config && cd $CURRENT
fi

# Update homebrew.
echo "Would you like to update homebrew and all its packages? (y/n) "
read -r response
if [[ $response =~ ^(yes|y)$ ]]; then
	bash "${OSZ_ROOT}/homebrew/update"
fi

# Update homebrew.
echo "Would you like to run \`brew prune\`? (y/n) "
read -r response
if [[ $response =~ ^(yes|y)$ ]]; then
	brew prune
fi

# Update npm packages.
echo "Would you like to update npm global packages? (y/n) "
read -r response
if [[ $response =~ ^(yes|y)$ ]]; then
	bash "${OSZ_ROOT}/node/update"
fi

# Update macOS software.
echo "Would you like to update macOS Apps? (y/n) "
read -r response
if [[ $response =~ ^(yes|y)$ ]]; then
	sudo softwareupdate --install --all
fi

# Update prezto / zsh.
echo "Would you like to update prezto (zsh)? (y/n) "
read -r response
if [[ $response =~ ^(yes|y)$ ]]; then
	zprezto-update
fi
