#!/usr/bin/env bash
# sets reasonable OS X defaults.

quicklook_plugins=(
	betterzipql
	epubquicklook
	qlcolorcode
	qlimagesize
	qlmarkdown
	qlprettypatch
	qlstephen
	quicklook-csv
	quicklook-json
	qlvideo
	the-unarchiver
	webpquicklook
)

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -e -p "[?] Where is OS Zimmee installed? " -i "$HOME/Projects/os-zimmee" reply
	OSZ_ROOT=$reply
fi

# Install quicklook plugins.
echo "[i] Installing quicklook plugins for MacOS..."
brew install "${quicklook_plugins[@]}"
echo "[i] Done installing quicklook plugins for MacOS."

# Install system settings.
read -p "[?] Do you want to configure MacOS system settings? (Y/n) " CONTINUE
CONTINUE=${CONTINUE:-y}
if [[ $CONTINUE =~ ^([yY][eE][sS]|[yY])$ ]]; then
	source ${OSZ_ROOT}/${macos}/install-system || ERROR_MSG+="[!] Not all MacOS system settings were configured. :(\n"
fi
