#!/usr/bin/env bash
# sets reasonable OS X defaults.

quicklook_plugins=(
	betterzipql
	epubquicklook
	qlcolorcode
	qlimagesize
	qlmarkdown
	qlprettypatch
	qlstephen
	quicklook-csv
	quicklook-json
	qlvideo
	the-unarchiver
	webpquicklook
)

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Install quicklook plugins.
echo "[i] Installing quicklook plugins for MacOS..."
brew install "${quicklook_plugins[@]}"
echo "[i] Done installing quicklook plugins for MacOS."

# Install system settings.
read -p "[?] Do you want to configure MacOS system settings? (Y/n) " continue
continue=${continue:-y}
if [[ $continue =~ ^([yY][eE][sS]|[yY])$ ]]; then
	source ${OSZ_ROOT}/${macos}/install-system || error_msg+="[!] Not all MacOS system settings were configured. :(\n"
fi
