#!/usr/bin/env bash

if [ -z $OSZ_ROOT ]; then
	read -e -p "[??] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_ROOT
fi

# Install karabiner-elements.
brew list --casks karabiner-elements || brew install karabiner-elements

# Symlink karabiner-elements.
mkdir -p ~/.config && ln -sf "${OSZ_ROOT}/karabiner-elements/karabiner.link" ~/.config/karabiner
