#!/usr/bin/env bash
# set up karabiner-elements
#
# bash karabiner-elements/setup

# Symlink karabiner-elements.
mkdir -p ~/.config && ln -sf "${OSZ_ROOT}/karabiner-elements/karabiner.link" ~/.config/karabiner
