#!/usr/bin/env bash
# set up karabiner-elements
#
# bash karabiner-elements/setup

# Load config.
if [[ -z $CONFIG__loaded ]]; then
	local script_path=${BASH_SOURCE[0]:-${(%):-%N}}
	CURRENT=${PWD} && cd -P "$(dirname $script_path)" && . ../config && cd $CURRENT
fi

# Symlink karabiner-elements.
mkdir -p ~/.config && ln -s "${OSZ_ROOT}/karabiner-elements/karabiner.link" ~/.config/karabiner
