#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Get config.
source "$OSZ_ROOT/fonts/config.sh"

# Install taps.
brew tap homebrew/cask-fonts

# Install fonts.
brew install "${CONFIG__BREW_FONTS[@]}"

echo "Installed fonts!"