#!/usr/bin/env bash

# Get config.
source ./config.sh

# Uninstall.
brew untap homebrew/cask-fonts

# Uninstall each font.
for FONT in ${CONFIG__BREW_FONTS[@]}; do
  echo 'Removing $FONT...'
  brew list --casks $FONT && brew uninstall $FONT
done
