#!/usr/bin/env bash

# Source configuration.
source ./config.sh

# Install homebrew if not already installed.
install_homebrew () {
	if [[ $(command -v brew) ]]; then
		echo "Homebrew already installed."
	else
		echo "Installing homebrew..."
		curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash /dev/stdin
	fi
}

# Install homebrew taps and apps.
install_homebrew_apps () {
	echo "Installing brew taps..."
	brew tap "${CONFIG__BREW_TAPS[@]}"

	echo "Installing homebrew apps..."
	brew install "${CONFIG__BREW_APPS[@]}"
}

# install homebrew & apps
install_homebrew || echo "[!!] Something went wrong with installing Homebrew... exiting."
install_homebrew_apps || echo "[!!] Something went wrong with installing Homebrew apps... exiting."
source ./update || echo "[!!] Something went wrong with updating Homebrew... exiting."
echo "Done!"
