#!/usr/bin/env bash

# Install homebrew if not already installed.
install_homebrew () {
	if [[ $(command -v brew) ]]; then
		echo "Homebrew already installed."
	else
		echo "Installing homebrew..."
		curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash /dev/stdin
	fi
}

# install homebrew & apps
install_homebrew || echo "[!] Something went wrong with installing Homebrew... exiting."
echo "[i] Done installing Homebrew!"
