#!/usr/bin/env bash

# Uninstall homebrew.
uninstall_homebrew () {
	echo "Uninstalling homebrew..."
	curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh | bash /dev/stdin
}

# Uninstall homebrew & apps
uninstall_homebrew_apps || echo "[!] Something went wrong with uninstalling Homebrew apps... exiting."
echo "[i] Done uninstalling homebrew!"
