#!/usr/bin/env bash
# installs and configures OS Zimmee

# update homebrew
echo "Updating homebrew..."
brew update && brew upgrade

# cleanup homebrew
read -p "Would you like to clean up all old homebrew packages? (y/n) " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
	brew cleanup
fi

brew doctor
