#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Install Node Version Manager (NVM).
brew install nvm

# Install Node versions.
mkdir ~/.nvm
ln -sf "$OSZ_ROOT/node/default-packages" ~/.nvm/default-packages
source $OSZ_ROOT/node/init.zsh
nvm install stable
nvm install node

# Set default node to stable.
nvm alias default stable
