#!/usr/bin/env bash
#
# installs node packages

install_node_packages () {
    # Update npm and install global modules.
    local count_installed=0 count_skipped=0
    for package in "${CONFIG__npm_globals[@]}"; do
        if npm list --depth 1 --global ${package} > /dev/null 2>&1; then
            log "${package} already installed."
            ((count_skipped++))
        else
            echo ''
            log "npm install -g ${package}" command
            npm install -g "${package}"
            (($count_installed++))
        fi
    done

    log "${BLUE}${count_installed}${END_COLOR} npm packages installed; ${BLUE}${count_skipped}${END_COLOR} already installed."
}

install_node_packages