#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
  read -e -p "[??] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_ROOT
fi

# Install Node Version Manager (NVM).
brew install nvm

# Install Node versions.
# mkdir ~/.nvm
ln -sf "$OSZ_ROOT/node/default-packages" ~/.nvm/default-packages
nvm install stable
nvm install node

# Set default node to stable.
nvm alias default stable
