#!/usr/bin/env bash
# installs node packages
#
# bash node/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
	local script_path=${BASH_SOURCE[0]:-${(%):-%N}}
	CURRENT=${PWD} && cd -P "$(dirname $script_path)" && . ../config && cd $CURRENT
fi

# Create Node Version Manager (NVM) directory.
mkdir ~/.nvm
nvm install node

# install_node_packages
npm install -g ${CONFIG__npm_globals[@]}
