#!/usr/bin/env bash

CONFIG__npm_globals=(
	"eslint"
	"prettier"
	"stylelint"
)

if [ -z $OSZ_PATH ]; then
	read -e -p "[??] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_PATH
fi

# Create Node Version Manager (NVM) directory.
mkdir ~/.nvm
nvm install node

# install_node_packages
npm install -g ${CONFIG__npm_globals[@]}
