#!/usr/bin/env bash

CONFIG__npm_globals=(
	"eslint"
  "pnpm"
	"prettier"
  "standardjs"
	"stylelint"
)

# Create Node Version Manager (NVM) directory.
mkdir ~/.nvm
nvm install node

# install_node_packages
npm install -g ${CONFIG__npm_globals[@]}
