#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
  read -e -p "[?] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_ROOT
fi

# Uninstall Node Version Manager (NVM).
brew list nvm && brew uninstall nvm

# Uninstall Node versions.
rm -rf "$NVM_DIR"
rm -rf ~/.nvm/default-packages
rm -rf ~/.nvm
rm -rf ~/.npm
