#!/usr/bin/env bash
#
# update amethyst

update_amethyst () {
	# this copies the amethyst plist file to the OSZ_ROOT so the OSZ repo has any latest changes I make to amethyst prefs
	\cp -rf "$HOME/Library/Preferences/com.amethyst.Amethyst.plist" "$OSZ_ROOT/amethyst/com.amethyst.Amethyst.plist" 
}

overwrite_handler "$OSZ_ROOT/amethyst/com.amethyst.Amethyst.plist" "$HOME/Library/Preferences/com.amethyst.Amethyst.plist" "${BLUE}amethyst${END}${BOLD} wants to update the plist file in ${MAGENTA}\$OSZ_ROOT/amethyst${END}${BOLD} to the latest." && update_amethyst