#!/usr/bin/env bash
# Set up for firefox.
# . firefox/setup

# Intro
echo 'Setting up Firefox...'

# For each directory inside firefox/profiles, create a firefox profile.
for dir in ${OSZ_ROOT}/firefox/profiles/*; do
	local user=$(basename ${dir})
	firefox -CreateProfile "$user ${dir}" || echo "[!!] Error creating firefox profile for ${user}"
	# if [[ -d "$dir" ]]; then
	# 	ln -sf "$dir" "/Volumes/Home/Library/Application Support/Firefox/Profiles"
	# fi
done

# Wrap up.
firefox -ProfileManager
echo '[ok] Firefox setup complete.'
echo '[i] Make sure to open `about:profiles` in Firefox and set your default profile.'
