#!/usr/bin/env bash
# set up karabiner
#
# bash karabiner/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
    CURRENT=${PWD} && cd -P "$( dirname "$0" )" && cd .. && . ./config && cd $CURRENT
fi

# symlink karabiner configuration
if [[ ! -e "~/.karabiner.d/configuration" ]]; then
	mkdir ~/.karabiner.d
	ln -s "${OSZ_ROOT}/karabiner/configuration.link" ~/.karabiner.d/configuration
else
	echo "~/.karabiner.d already exists. Karabiner configuration files will not be copied."
fi