#!/usr/bin/env bash

install_zsh=false
install_ohmyzsh=false
ohmyzsh_defaults_filename=.zshrc-oh-my-zsh-defaults

# [[[ Gather user input

if [ -z $OSZ_ROOT ]; then
	read -e -p "[??] Where is OS Zimmee installed? " -i "$HOME/Projects/os-zimmee" reply
	OSZ_ROOT=$reply
fi

if [ ! $(which zsh)  ]; then
	install_zsh=true
else
	read -p "Reinstall zsh? (Yes|no) " reply
	if [[ $reply =~ ^(yes|y)$ ]]; then
		install_zsh=true
	fi
fi

if [ ! -d "$HOME/.oh-my-zsh"  ]; then
	install_ohmyzsh=true
else
	read -p "Reinstall oh-my-zsh? (Yes|no) " reply
	if [[ $reply =~ ^(yes|y)$ ]]; then
		install_ohmyzsh=true
	fi
fi

# ]]]

# [[[ Install zsh

# Install zsh and its homebrew dependencies.
if [ $install_zsh = true ]; then
	brew install zsh zsh-completions direnv
fi

# Install oh-my-zsh.
if [ $install_ohmyzsh = true ]; then
	rm -rf "$HOME/.oh-my-zsh"
	# Download oh-my-zsh.
	curl -s https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | source /dev/stdin
	# Replace .zshrc and save oh-my-zsh's .zshrc as .zshrc-oh-my-zsh.
	mv -f "$HOME/.zshrc" "$OSZ_ROOT/zsh/$ohmyzsh_defaults_filename"
fi

# ]]]

# [[[ Symlink .zshrc.
rm -rf "$HOME/.zshrc"
ln -s "$OSZ_ROOT/zsh/.zshrc" "$HOME/.zshrc"
# ]]]

# [[[ Set up zsh as default shell.
if [ $SHELL != /bin/zsh ]; then
	chsh -s /usr/local/bin/zsh
fi
echo '[ok] Success! ZSH is set up.'
# ]]]
