#!/usr/bin/env bash
# set up ZSH
#
# bash zsh/setup

## Load config.
if [[ -z $CONFIG__loaded ]]; then
	CURRENT=${PWD} && cd -P "$( dirname "$0" )" && cd .. && . ./config && cd $CURRENT
fi

## Set up zsh as default shell.
if [[ $SHELL != /bin/zsh ]]; then
	echo "Changing default shell to ZSH..."
	chsh -s /bin/zsh
fi

## Ask to start fresh.
REFRESH=false
read -p "Remove all current zsh and prezto configuration and start fresh ('no' will link any missing zsh/prezto config files)? "
if [[ $REPLY =~ ^(yes|y)$ ]]; then
	REFRESH=true
	rm -rf ${OSZ_ROOT}/zsh/zprezto.link || echo "Couldn't remove ${OSZ_ROOT}/zsh/zprezto.link."
fi

## Add prezto submodule.
if [[ $REFRESH = true ]]; then
	git clone --recursive https://github.com/sorin-ionescu/prezto.git "${OSZ_ROOT}/zsh/zprezto.link" && cd ${OSZ_ROOT}/zsh/zprezto.link && git pull && git submodule update --init --recursive || echo "Error cloning prezto."
fi

## Set up prezto config files.
for rcfile in $(find ${OSZ_ROOT}/zsh/zprezto.link/runcoms/* -name '*' -not -name 'README.md' -not -name 'zshrc' -not -name 'zpreztorc'); do
	dest="$HOME/.$(basename "${rcfile}")"
	if [[ $REFRESH = true ]]; then
		ln -sf "$rcfile" "$dest"
	else
		ln -s "$rcfile" "$dest" || echo "Skipped $rcfile."
	fi
done

## Symlink other *.link files.
for dotfile in $(find ${OSZ_ROOT}/zsh/ -name '*.link*'); do
	dest="$HOME/.$(basename "${dotfile%.link*}")"
	if [[ $REFRESH = true ]]; then
		ln -sf "$dotfile" "$dest"
	else
		ln -s "$dotfile" "$dest" || echo "Skipped $dotfile."
	fi
done
