#!/usr/bin/env bash
# set up ZSH
#
# . zsh/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
	CURRENT=${PWD} && cd -P "$( dirname "$0" )" && cd .. && . ./config && cd $CURRENT
fi

# change zsh to default shell
echo "Changing default shell to ZSH..."
chsh -s /bin/zsh

# set up ZSH dotfiles
echo "Setting up ZSH dotfiles..."
ln -s ${OSZ_ROOT}/zprezto.link ~/.zprezto
for dotfile in $(find -H ${OSZ_ROOT}/zsh/*.link); do
    dest="$HOME/.$(basename "${dotfile%.*}")"
    ln -s "$dotfile" "$dest"
done
