#!/usr/bin/env bash

# Install iTerm.
brew install iterm2

# Integrate with ZSH.
echo 'Integrating with ZSH...'
curl -L https://iterm2.com/shell_integration/zsh \
-o ~/.iterm2_shell_integration.zsh
echo 'Done!'
