#!/usr/bin/env bash

if [ -z $OSZ_ROOT ]; then
	read -e -p "[??] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_ROOT
fi

# Symlink hammerspoon.
ln -sf "${OSZ_ROOT}/hammerspoon/hammerspoon.link" ~/.hammerspoon
