#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Symlink hammerspoon.
ln -sf "${OSZ_ROOT}/hammerspoon/hammerspoon.link" ~/.hammerspoon
