#!/usr/bin/env bash
# installs and configures OS Zimmee
#
# . homebrew/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
	CURRENT=${PWD} && cd -P "$(dirname ${BASH_SOURCE[0]})" && . ../config && cd $CURRENT
fi

# symlink hammerspoon
ln -s "${OSZ_ROOT}/hammerspoon/hammerspoon.link" ~/.hammerspoon
