#!/usr/bin/env bash
# installs and configures OS Zimmee
#
# . homebrew/setup

# load config
if [[ -z $CONFIG__loaded ]]; then
	local script_path=${BASH_SOURCE[0]:-${(%):-%N}}
	CURRENT=${PWD} && cd -P "$(dirname $script_path)" && . ../config && cd $CURRENT
fi

# symlink hammerspoon
ln -s "${OSZ_ROOT}/hammerspoon/hammerspoon.link" ~/.hammerspoon
