#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
  read -e -p "[??] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_ROOT
fi

# Install node v12.19.0 and create marqeta alias for it.
defaults export com.manytricks.Moom "$OSZ_ROOT/moom/Moom.plist"Moom.plist
