#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
  read -e -p "[??] Where is OS Zimmee installed? " -i "~/Projects/os-zimmee" OSZ_ROOT
fi

# Install moom.
brew install moom

# Import moom preferences.
defaults import com.manytricks.Moom "$OSZ_ROOT/moom/Moom.plist"
