#!/usr/bin/env bash

# Get $OSZ_ROOT.
if [ -z $OSZ_ROOT ]; then
	read -p "[?] Where is OS Zimmee installed? " reply
	OSZ_ROOT=${reply:-$HOME/Projects/os-zimmee}
fi

# Install moom.
brew install moom

# Import moom preferences.
defaults import com.manytricks.Moom "$OSZ_ROOT/moom/Moom.plist"
